pipelines:
  branches:
    test/deploy:
    - step:
        services:
          - docker
        script: # Modify the commands below to build your repository.
          - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
     #     - curl https://cli-assets.heroku.com/install.sh | sh
     #     - heroku container:login
     #     - heroku container:push web -a $HEROKU_APP_NAME
     #     - heroku container:release web -a $HEROKU_APP_NAME
    - step:
        name: url
        script:
          - echo https://arx-design.herokuapp.com/

