pipelines:
  branches:
    master:
    - step:
        services:
          - docker
        script: # Modify the commands below to build your repository.
          - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
    - step:
        name: url
        script:
          - echo https://arx-design.herokuapp.com/

